### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chisi21** [Mcbeany/CustomSound#1]
sorry, I tried but it didn't work, is there something wrong with me.
I only entered the 2 second ogg audio file in plugin_data, and when I used the command to play, I didn't hear anything

**Comment by Mcbeany** [comment]
Thanks for your feedback!
But make sure you correctly convert your audio file to .ogg.
And it may take 2-5 seconds to play the sound.

If you are sure that is the cause of the plugin, please leave more information such as video or error log.

**Comment by chisi21** [comment]
> Thanks for your feedback!
> But make sure you correctly convert your audio file to .ogg.
> And put it in the right folder `plugin_data/CustomSound/sounds`, it may take 2-5 seconds to play the sound when you run the command.
> 
> If you are sure that is the cause of the plugin, please leave more information such as video or error log.

yeah thanks for it...
but i want to ask if your bank plugin will be continued? I have a new issue on your plugin bank. I think the plugin is very good, and I hope it will continue :D

**Comment by Mcbeany** [comment]
My Bank plugin is still unpublished and it has been discontinued. But i will rewrite it soon

**Comment by chisi21** [comment]
> My Bank plugin is still unpublished and it has been discontinued. But i will rewrite it soon

thanks for respon :D i will wait for it

**Comment by chisi21** [comment]
> My Bank plugin is still unpublished and it has been discontinued. But i will rewrite it soon

Hey, sorry i wanna ask
For API playsound, how do i write code to get $position ?

**Comment by Mcbeany** [comment]
Player is a position
