### ISSUE TITLE
[FR] Movement and sound for the other players

### ISSUE THREAD

**Issue by MrBlasyMSK** [Mcbeany/CustomSound#2]
Implement an option that when playing it in one player will be heard by others, and that the movement follows

I do not know if this is possible, what others hear if it does the normal / playsound, but the movement I have no idea if it can be done.

And you could add in the config an option of

Follow sound on movement: True
Other players may hear it: True

**Comment by Mcbeany** [comment]
first, have you read this? https://github.com/Mcbeany/CustomSound#api
second, no, now it is not possible

**Comment by MrBlasyMSK** [comment]
I'm not a developer so the API is of no use to me
